run:
  tests: false
linters:
  enable-all: true
  disable:
    - interfacer
    - goerr113
linters-settings:
  lll:
    line-length: 140
  goimports:
    local-prefixes: dateservice
  gocritic:
    enabled-tags:
      - style
      - experimental
